version: '3.4' # Specify docker-compose version
services:
   web: # Name of the frontend service
      build: .
      restart: always
      ports:
      - "19006:19006"
      - "19000:19000"
      volumes: # Mount host path in the container
      - .:/opt/sport-tracker-web
      - /opt/sport-tracker-web/app/node_modules
















# version: '3.7' # Specify docker-compose version
# services:
#    expo: # Name of the frontend service
#       container_name: sport-tracker-front
#       build: . # Specify the directory of the Dockerfile
#       ports:
#          - 19000:19000 # Specify port-forwarding
#          - 19001:19001
#          - 19002:19002
#       volumes: # Mount host path in the container
#          - .:/opt/sport-tracker-web
#          - /opt/sport-tracker-web/app/node_modules











      # environment:
      #    - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 
      #    - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.44